# docker-compose.yml (in your project root)
version: '3.8'

services:
  db:
    image: postgres:15-alpine # Use a specific version for consistency
    environment:
      POSTGRES_DB: expense_tracker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d expense_tracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: . # Build from the Dockerfile in the current directory
    ports:
      - "8080:8080" # Map app port to host port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expense_tracker_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy # Wait for DB to be healthy
    restart: on-failure # Always restart if it fails

volumes:
  db_data: # Define the named volume